In [2]:
import numpy as np

In [46]:
x = np.linspace(-1,1,11);
y = np.cos(np.pi * x);
x

array([-1. , -0.8, -0.6, -0.4, -0.2,  0. ,  0.2,  0.4,  0.6,  0.8,  1. ])

In [6]:
#Operaciones matematicas elementales
#np.add, np.subtract, np.multiply, np.divide, np.power, np.remainder, np.reciprocal, np.abs, np.round

np.add(np.sin(x)**2, np.cos(x)**2)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [7]:
# algunas funciones de interes
#np.mean, np.std, np.var, np.sum, np.prod, np.cumsum, np.win, np.max, np.argmin, np.all, np.any, (Lógicos)

data = np.random.normal(size=(5,10,15)) #crear un arreglo de distribución normal
data

array([[[-7.70599906e-01,  7.36966083e-01,  5.00245480e-01,
          6.56449137e-01,  5.98683531e-02, -1.29378229e+00,
          8.70665396e-02, -9.67185157e-01, -1.15107719e+00,
          3.98468638e-01, -1.59176471e+00, -1.41953231e+00,
          5.42111064e-01, -7.63320254e-01,  5.87300087e-01],
        [ 1.18659413e+00, -1.30672586e+00, -2.33367034e-02,
         -9.63797946e-02, -1.02667822e+00,  1.10762293e+00,
         -1.67587823e+00,  1.54633234e+00, -6.11903719e-01,
          2.03645193e-01,  3.44967278e-01, -1.08718049e+00,
          1.98991470e-01,  3.23970262e-01, -6.47134295e-01],
        [ 9.00812762e-01, -9.97739413e-01,  4.75685283e-01,
         -3.89576128e-01,  7.90553577e-01,  1.51499339e+00,
          3.25779089e-01, -6.89863985e-01,  8.09359334e-01,
          3.18655827e-01, -1.65279611e+00,  3.88215275e-01,
         -4.42661886e-02, -8.19983656e-01,  1.25833829e+00],
        [ 1.06181143e+00,  1.02162552e-01, -7.37865883e-01,
          1.49578702e+00, -2.09968014

In [19]:
data = np.arange(1,10).reshape(3,3) #crear un arreglo 3x3 de númerosn entre 1 y 10
data.sum(axis=1) #suma de filas del arreglo

array([ 6, 15, 24])

In [20]:
#Operaciones sobre arreglos
data = np.arange(9).reshape(3,3)
data

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [22]:
#la transpuesta
np.transpose(data)

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [27]:
#rotar los elementos 90°
np.rot90(data)

array([[2, 5, 8],
       [1, 4, 7],
       [0, 3, 6]])

### operaciones entre matricez y vectores

In [34]:
# Resuimen de funciones
# np.dot          Producnto punto entre vectores
# np.inner        Producto por escalar
# no.cross        Producto cruz entre vectores
# np.tensordot    Producto tensorial
# np.outer        Producto externo
# np.kron         Producto de kronecker

A = np.arange(1,7).reshape(2,3)
B = np.arange(1,7).reshape(3,2)
c = np.dot(A,B)
print ("tamaño 2x3 \n", A, "\n \n  tamaño 3x2 \n", B, " \n \n \n ", c)

tamaño 2x3 
 [[1 2 3]
 [4 5 6]] 
 
  tamaño 3x2 
 [[1 2]
 [3 4]
 [5 6]]  
 
 
  [[22 28]
 [49 64]]


In [35]:
c = np.inner(2,A)
c 

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [36]:
c = np.dot(B,A)
c

array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51]])

In [45]:
A = np.arange(9).reshape(3,3)   #tamaño 3x3
X = np.arange(3)                #tamaño 1x3
print (A,X)
np.dot(A,X)

x_x = np.inner(X,X)             # la forma equivalente x_x = np.dot(x,x)
x_x

X_kron = np.kron(X,X)
X_kron

[[0 1 2]
 [3 4 5]
 [6 7 8]] [0 1 2]


array([0, 0, 0, 0, 1, 2, 0, 2, 4])

In [49]:
np.kron(np.ones((3,3)), np.identity(3))

array([[1., 0., 0., 1., 0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 1., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0., 1., 0., 0., 1.],
       [1., 0., 0., 1., 0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 1., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0., 1., 0., 0., 1.],
       [1., 0., 0., 1., 0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 1., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0., 1., 0., 0., 1.]])

In [ ]:
#help(max)          El comando help da información de ayuda sobre la función en el argumento


In [50]:
a = np.array([1,2,3,4,5,6,7])
a?   # nos da toda la información y características de la variable a