# Arreglos multidimencionales

In [5]:
# arreglos multidimencionles
import numpy as np

In [6]:
f = lambda m,n: n+10*m
A= np.fromfunction(f,(6,6), dtype= float)
A

array([[ 0.,  1.,  2.,  3.,  4.,  5.],
       [10., 11., 12., 13., 14., 15.],
       [20., 21., 22., 23., 24., 25.],
       [30., 31., 32., 33., 34., 35.],
       [40., 41., 42., 43., 44., 45.],
       [50., 51., 52., 53., 54., 55.]])

In [7]:
print (A[1,:], " la columna 0 \n") 
print (A[0,:], " la fila 0 \n")
print (A[:3,:3], " subloque matriz 3x3 superior-izquierdo \n") 
print (A[3:,:3], " subloque matriz 3x3 superior-derecho \n") 
print (A[:3,:6], " subloque matriz 3x6 \n") 
print (A[:3,3:], " primeras 3 columnas, últimas 3 filas \n") 
print (A[3:,:3], " últimas 3 columnas, primeras 3 filas \n") 
print (A[:,:], " Toda la matriz \n")

[10. 11. 12. 13. 14. 15.]  la columna 0 

[0. 1. 2. 3. 4. 5.]  la fila 0 

[[ 0.  1.  2.]
 [10. 11. 12.]
 [20. 21. 22.]]  subloque matriz 3x3 superior-izquierdo 

[[30. 31. 32.]
 [40. 41. 42.]
 [50. 51. 52.]]  subloque matriz 3x3 superior-derecho 

[[ 0.  1.  2.  3.  4.  5.]
 [10. 11. 12. 13. 14. 15.]
 [20. 21. 22. 23. 24. 25.]]  subloque matriz 3x6 

[[ 3.  4.  5.]
 [13. 14. 15.]
 [23. 24. 25.]]  primeras 3 columnas, últimas 3 filas 

[[30. 31. 32.]
 [40. 41. 42.]
 [50. 51. 52.]]  últimas 3 columnas, primeras 3 filas 

[[ 0.  1.  2.  3.  4.  5.]
 [10. 11. 12. 13. 14. 15.]
 [20. 21. 22. 23. 24. 25.]
 [30. 31. 32. 33. 34. 35.]
 [40. 41. 42. 43. 44. 45.]
 [50. 51. 52. 53. 54. 55.]]  Toda la matriz 



In [8]:
print (A[::2, ::2], " elementos espaciados \n")
print (A[::2, ::3], " elementos espaciados \n")
print (A[1::2, 1::3], " elementos espaciados iniciando desde 1 espaciados dos unidades en fila y 3 en columnas \n")
print (A[1,2], " elemento con indice 1-2")

[[ 0.  2.  4.]
 [20. 22. 24.]
 [40. 42. 44.]]  elementos espaciados 

[[ 0.  3.]
 [20. 23.]
 [40. 43.]]  elementos espaciados 

[[11. 14.]
 [31. 34.]
 [51. 54.]]  elementos espaciados iniciando desde 1 espaciados dos unidades en fila y 3 en columnas 

12.0  elemento con indice 1-2


In [9]:
B = A [1:5, 1:5]
print (B, " submatriz de posiciones 1 hasta 5 en indices \n")
B[:,:]=0
print (B, " \n")

print (A)

[[11. 12. 13. 14.]
 [21. 22. 23. 24.]
 [31. 32. 33. 34.]
 [41. 42. 43. 44.]]  submatriz de posiciones 1 hasta 5 en indices 

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]  

[[ 0.  1.  2.  3.  4.  5.]
 [10.  0.  0.  0.  0. 15.]
 [20.  0.  0.  0.  0. 25.]
 [30.  0.  0.  0.  0. 35.]
 [40.  0.  0.  0.  0. 45.]
 [50. 51. 52. 53. 54. 55.]]


In [10]:
C = B[1:3, 1:3].copy()
C[:,:] = 1,0
print (C , " \n \n", B)

[[1. 0.]
 [1. 0.]]  
 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
A = np.linspace(0,1,11)
A

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [ ]:
A[np.array([0,2,4,7])]

array([0. , 0.2, 0.4, 0.7])

In [ ]:
A >= 0.5

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [ ]:
A[A >= 0.5] # retorna los valores donde es TRUE

array([0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [ ]:
A = np.arange(10)
indexes= [2,4,6]
B = A[indexes]
B[0] = -1 #no altera las entradas de A
# A[indexes]= -1
# de forma booleana
B = A[A>5]
B [0] = -1
A[A>5]= -1 # las entradas de A se alteran
A


array([ 0,  1,  2,  3,  4,  5, -1, -1, -1, -1])

### reformando y reescalando arreglos

In [ ]:
data = np.array([[1,2],[3,4]])
data

array([[1, 2],
       [3, 4]])

In [ ]:
data = np.array([[1,2],[3,4], [5,6]])
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
data.flatten()

array([1, 2, 3, 4, 5, 6])

In [11]:
data= np.arange (0,5)
column = data[:,np.newaxis]
row = data[np.newaxis,1]
row

array([1])

In [ ]:
data = np.arange(0,5)
stack1 = np.hstack((data, data,data, data,data, data)) #copias horizontales
stack2 = np.vstack((data, data,data, data,data, data)) # copias verticales
print (stack1, "\n \n", stack2)

[0 1 2 3 4 0 1 2 3 4 0 1 2 3 4 0 1 2 3 4 0 1 2 3 4 0 1 2 3 4] 
 
 [[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]
